# Generated by Django 3.2.8 on 2021-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/NoImg.png', upload_to='images/'),
        ),
    ]
